// packages/sdk/react/src/node.tsx
import React, { createContext, useContext, useMemo } from "react";
import { evaluateDynamicValue } from "@openscene/javascript";
import { useOpenScene } from "./context.ts";

export interface OpenSceneNodeContextValue {
  nodeId: string | null;
  nodeAttrs: { "data-node-id"?: string };
}

const OpenSceneNodeContext = createContext<OpenSceneNodeContextValue>({
  nodeId: null,
  nodeAttrs: {},
});

export function OpenSceneNodeProvider(props: {
  nodeId: string;
  children: React.ReactNode;
}): React.JSX.Element {
  const value = useMemo<OpenSceneNodeContextValue>(
    () => ({
      nodeId: props.nodeId || null,
      nodeAttrs: props.nodeId ? { "data-node-id": props.nodeId } : {},
    }),
    [props.nodeId],
  );

  return (
    <OpenSceneNodeContext.Provider value={value}>{props.children}</OpenSceneNodeContext.Provider>
  );
}

export function useOpenSceneNode(): OpenSceneNodeContextValue {
  return useContext(OpenSceneNodeContext);
}

export interface PrimitiveProps {
  props: Record<string, unknown>;
  children?: React.ReactNode;
  emit: (event: string) => void;
  on: (event: string) => { emit: () => void; shouldPreventDefault: boolean; bound: boolean };
}

export function useResolvedProps(rawProps: Record<string, unknown>): Record<string, unknown> {
  try {
    const context = useOpenScene();
    const doc = context.snapshot.document;
    const docState = (doc?.spec?.state as Record<string, unknown> | undefined) ?? {};
    const storeState = context.snapshot.runtimeStore?.getSnapshot() ?? {};
    const state = { ...docState, ...storeState };
    return evaluateDynamicValue(rawProps, state) as Record<string, unknown>;
  } catch {
    return rawProps;
  }
}

export function View(props: PrimitiveProps): React.JSX.Element {
  const node = useOpenSceneNode();
  const resolved = useResolvedProps(props.props);
  const className =
    typeof resolved.className === "string"
      ? (resolved.className as string)
      : typeof resolved.class === "string"
        ? (resolved.class as string)
        : undefined;
  const style = resolved.style as React.CSSProperties | undefined;

  return (
    <div {...node.nodeAttrs} className={className} style={style}>
      {props.children}
    </div>
  );
}

export function Text(props: PrimitiveProps): React.JSX.Element {
  const node = useOpenSceneNode();
  const resolved = useResolvedProps(props.props);
  const val = resolved.text ?? resolved.label;
  const text =
    typeof val === "string" || typeof val === "number" || typeof val === "boolean"
      ? String(val)
      : undefined;
  const className =
    typeof resolved.className === "string"
      ? (resolved.className as string)
      : typeof resolved.class === "string"
        ? (resolved.class as string)
        : undefined;
  const style = resolved.style as React.CSSProperties | undefined;

  return (
    <span {...node.nodeAttrs} className={className} style={style}>
      {text ?? props.children}
    </span>
  );
}

export function Button(props: PrimitiveProps): React.JSX.Element {
  const node = useOpenSceneNode();
  const resolved = useResolvedProps(props.props);
  const val = resolved.label ?? resolved.text;
  const label =
    typeof val === "string" || typeof val === "number" || typeof val === "boolean"
      ? String(val)
      : undefined;
  const className =
    typeof resolved.className === "string"
      ? (resolved.className as string)
      : typeof resolved.class === "string"
        ? (resolved.class as string)
        : undefined;
  const style = resolved.style as React.CSSProperties | undefined;
  const disabled = resolved.disabled === true;
  const type =
    resolved.type === "submit" || resolved.type === "reset"
      ? (resolved.type as "submit" | "reset")
      : "button";

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    const press = props.on("press");
    if (press.shouldPreventDefault) event.preventDefault();
    press.emit();
  };

  return (
    <button
      {...node.nodeAttrs}
      type={type}
      disabled={disabled}
      className={className}
      style={style}
      onClick={handleClick}
    >
      {label ?? props.children}
    </button>
  );
}

// packages/sdk/solid-v2/src/node.tsx
import { createContext, useContext } from "solid-js";
import type { JSX } from "@solidjs/web";
import { evaluateDynamicValue } from "@openscene-ai/javascript";
import { useOpenScene } from "./context.js";

export interface OpenSceneNodeContextValue {
  nodeId: string | null;
  nodeAttrs: { "data-node-id"?: string };
}

const OpenSceneNodeContext = createContext<OpenSceneNodeContextValue>({
  nodeId: null,
  nodeAttrs: {},
});

export function OpenSceneNodeProvider(props: {
  nodeId: string;
  children: JSX.Element;
}): JSX.Element {
  return (
    <OpenSceneNodeContext
      value={{ nodeId: props.nodeId, nodeAttrs: { "data-node-id": props.nodeId } }}
    >
      {props.children}
    </OpenSceneNodeContext>
  );
}

export function useOpenSceneNode(): OpenSceneNodeContextValue {
  return useContext(OpenSceneNodeContext);
}

export interface PrimitiveProps {
  props: Record<string, unknown>;
  children?: JSX.Element;
  emit: (event: string) => void;
  on: (event: string) => { emit: () => void; shouldPreventDefault: boolean; bound: boolean };
}

function useResolvedProps(rawProps: Record<string, unknown>): Record<string, unknown> {
  try {
    const context = useOpenScene();
    const doc = context.snapshot().document;
    const docState = (doc?.spec?.state as Record<string, unknown> | undefined) ?? {};
    const storeState = context.snapshot().runtimeStore?.getSnapshot() ?? {};
    const state = { ...docState, ...storeState };
    return evaluateDynamicValue(rawProps, state) as Record<string, unknown>;
  } catch {
    return rawProps;
  }
}

export function View(props: PrimitiveProps): JSX.Element {
  const node = useOpenSceneNode();
  const resolved = () => useResolvedProps(props.props);
  const className = () =>
    typeof resolved().className === "string"
      ? (resolved().className as string)
      : typeof resolved().class === "string"
        ? (resolved().class as string)
        : undefined;
  const style = () => resolved().style;
  return (
    <div {...node.nodeAttrs} class={className()} style={style() as JSX.CSSProperties}>
      {props.children}
    </div>
  );
}

export function Text(props: PrimitiveProps): JSX.Element {
  const node = useOpenSceneNode();
  const resolved = () => {
    const res = useResolvedProps(props.props);
    console.log(`[OpenScene Solid Node] Text (#${node.nodeId}) props evaluated:`, {
      raw: props.props,
      resolved: res,
    });
    return res;
  };
  const text = () => {
    const val = resolved().text ?? resolved().label;
    return typeof val === "string" || typeof val === "number" || typeof val === "boolean"
      ? String(val)
      : undefined;
  };
  const className = () =>
    typeof resolved().className === "string"
      ? (resolved().className as string)
      : typeof resolved().class === "string"
        ? (resolved().class as string)
        : undefined;
  const style = () => resolved().style;
  return (
    <span {...node.nodeAttrs} class={className()} style={style() as JSX.CSSProperties}>
      {text() ?? props.children}
    </span>
  );
}

export function Button(props: PrimitiveProps): JSX.Element {
  const node = useOpenSceneNode();
  const resolved = () => useResolvedProps(props.props);
  const label = () => {
    const val = resolved().label ?? resolved().text;
    return typeof val === "string" || typeof val === "number" || typeof val === "boolean"
      ? String(val)
      : undefined;
  };
  const className = () =>
    typeof resolved().className === "string"
      ? (resolved().className as string)
      : typeof resolved().class === "string"
        ? (resolved().class as string)
        : undefined;
  const style = () => resolved().style;
  const disabled = () => resolved().disabled === true;
  const type = () =>
    resolved().type === "submit" || resolved().type === "reset"
      ? (resolved().type as "submit" | "reset")
      : "button";
  const handleClick = (event: MouseEvent) => {
    const press = props.on("press");
    console.log(`[OpenScene Event] Button (#${node.nodeId}) clicked! Emitting "press" event:`, {
      bound: press.bound,
      shouldPreventDefault: press.shouldPreventDefault,
    });
    if (press.shouldPreventDefault) event.preventDefault();
    press.emit();
  };
  return (
    <button
      {...node.nodeAttrs}
      type={type()}
      disabled={disabled()}
      class={className()}
      style={style() as JSX.CSSProperties}
      onClick={handleClick}
    >
      {label() ?? props.children}
    </button>
  );
}
